# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   initials: ' cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Team.create(city: 'Arizona', team: 'Cardinals', color1: '97233F', color2: '000000', helmet: '-90px -90px')
Team.create(city: 'Atlanta', team: 'Falcons', color1: 'A71930', color2: '000000', helmet: '-270px -180px')
Team.create(city: 'Baltimore', team: 'Ravens ', color1: 'A71930', color2: '000000', helmet: '-395px -360px')
Team.create(city: 'Buffalo', team: 'Bills', color1: '00338D', color2: 'C60C30', helmet: '-180px 0')
Team.create(city: 'Carolina', team: 'Panthers ', color1: '0085CA', color2: '000000', helmet: '-340px 0')
Team.create(city: 'Chicago', team: 'Bears', color1: '000000', color2: 'C83803', helmet: '0 0')
Team.create(city: 'Cincinnati', team: 'Bengals', color1: '000000', color2: 'C83803', helmet: '-90px 0')
Team.create(city: 'Cleveland', team: 'Browns ', color1: 'FB4F14', color2: '22150C', helmet: '-360px 0')
Team.create(city: 'Dallas', team: 'Cowboys', color1: '002244', color2: 'B0B7BC', helmet: '0 -180px')
Team.create(city: 'Denver', team: 'Broncos', color1: '002244', color2: 'FB4F14', helmet: '-270px 0')
Team.create(city: 'Detroit', team: 'Lions', color1: '005A8B', color2: 'B0B7BC', helmet: '-270px -270px')
Team.create(city: 'Green Bay', team: 'Packers', color1: '203731', color2: 'FFB612', helmet: '-340px -270px')
Team.create(city: 'Houston', team: 'Texans', color1: '03202F', color2: 'A71930', helmet: '-305px -360px')
Team.create(city: 'Indianapolis', team: 'Colts', color1: '002C5F', color2: 'A5ACAF', helmet: '-340px -90px')
Team.create(city: 'Jacksonville', team: 'Jaguars', color1: '000000', color2: '006778', helmet: '-90px -270px')
Team.create(city: 'Kansas City', team: 'Chiefs', color1: 'E31837', color2: 'FFB612', helmet: '-270px -90px')
Team.create(city: 'Miami', team: 'Dolphins', color1: '008E97', color2: 'F58220', helmet: '-90px -180px')
Team.create(city: 'Minnesota', team: 'Vikings', color1: '4F2683', color2: 'FFC62F', helmet: '-540px -180px')
Team.create(city: 'New England', team: 'Patriots', color1: '002244', color2: 'C60C30', helmet: '-540px 0')
Team.create(city: 'New Orleans', team: 'Saints', color1: '9F8958', color2: '000000', helmet: '-540px -90px')
Team.create(city: 'New York', team: 'Giants', color1: '0B2265', color2: 'A71930', helmet: '0 -270px')
Team.create(city: 'New York', team: 'Jets', color1: '203731', color2: 'FFFFFF', helmet: '-180px -270px')
Team.create(city: 'Oakland', team: 'Raiders', color1: 'A5ACAF', color2: '000000', helmet: '-360px -270px')
Team.create(city: 'Philadelphia', team: 'Eagles', color1: '004953', color2: 'A5ACAF', helmet: '-180px -180px')
Team.create(city: 'Pittsburgh', team: 'Steelers', color1: '000000', color2: 'FFB612', helmet: '-215px -360px')
Team.create(city: 'Saint Louis', team: 'Rams', color1: '002244', color2: 'B3995D', helmet: '-540px -270px')
Team.create(city: 'San Diego', team: 'Chargers', color1: '002244', color2: 'FFB612', helmet: '-180px -90px')
Team.create(city: 'San Francisco', team: '49ers', color1: 'AA0000', color2: 'B3995D', helmet: '-360px -180px')
Team.create(city: 'Seattle', team: 'Seahawks', color1: '002244', color2: '69BE28', helmet: '-125px -360px')
Team.create(city: 'Tampa Bay', team: 'Buccaneers', color1: 'D50A0A', color2: '34302B', helmet: '0 -90px')
Team.create(city: 'Tennessee', team: 'Titans', color1: '002244', color2: 'C60C30', helmet: '-360px -180px')
Team.create(city: 'Washington', team: 'Redskins', color1: '773141', color2: 'FFB612', helmet: '-360px -90px')

Pool.create(name: 'JoJo', email: 'jojo@yahoo.com', passcode: 'nfl2016', hometeam: 'Panthers', homecity: 'Carolina', homecolor1: '0085CA', homecolor2: '000000', homehelmet: '-455px 0', awayteam: 'Broncos', awaycity: 'Denver', awaycolor1: '002244', awaycolor2: 'FB4F14', awayhelmet: '-270px 0', x0: '6', x1: '0', x2: '8', x3: '7', x4: '5', x5: '2', x6: '9', x7: '4', x8: '3', x9: '1', y0: '6', y1: '7', y2: '8', y3: '9', y4: '2', y5: '4', y6: '0', y7: '1', y8: '3', y9: '5')

# Box.create(firstname: 'fn', lastname: 'ln', initials: 'F.L.', boxid: '0')
# Box.create(firstname: 'fn', lastname: 'ln', initials: 'F.L.', boxid: '0')

Box.create(firstname: 'RACE', lastname: ' ', initials: 'R.', boxid: '0', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '1', poolid: '1')
Box.create(firstname: 'JAY', lastname: ' ', initials: 'JAY', boxid: '2', poolid: '1')
Box.create(firstname: 'CARTEL', lastname: ' ', initials: 'C.', boxid: '3', poolid: '1')
Box.create(firstname: 'DAWNA', lastname: ' ', initials: 'D.', boxid: '4', poolid: '1')
Box.create(firstname: 'SANDI', lastname: 'E.', initials: 'S.E.', boxid: '5', poolid: '1')
Box.create(firstname: 'ED', lastname: ' ', initials: 'E.A.', boxid: '6', poolid: '1')
Box.create(firstname: 'KAKL', lastname: ' ', initials: 'K', boxid: '7', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '8', poolid: '1')
Box.create(firstname: 'RACE', lastname: ' ', initials: 'R', boxid: '9', poolid: '1')
Box.create(firstname: 'CARTEL', lastname: ' ', initials: 'C.', boxid: '10', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '11', poolid: '1')
Box.create(firstname: 'GARY', lastname: 'E.', initials: 'G.E.', boxid: '12', poolid: '1')
Box.create(firstname: 'KYLIE', lastname: ' ', initials: 'KY', boxid: '13', poolid: '1')
Box.create(firstname: 'ASHLYN', lastname: ' ', initials: 'A', boxid: '14', poolid: '1')
Box.create(firstname: 'DENNIS', lastname: 'T.', initials: 'D.T.', boxid: '15', poolid: '1')
Box.create(firstname: 'DAWNA', lastname: ' ', initials: 'D.', boxid: '16', poolid: '1')
Box.create(firstname: 'STEVE', lastname: 'R.', initials: 'S.R.', boxid: '17', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '18', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '19', poolid: '1')
Box.create(firstname: 'JALI', lastname: ' ', initials: 'JA', boxid: '20', poolid: '1')
Box.create(firstname: 'GREG', lastname: 'S.', initials: 'G.S.', boxid: '21', poolid: '1')
Box.create(firstname: 'CARTEL', lastname: ' ', initials: 'C', boxid: '22', poolid: '1')
Box.create(firstname: 'CINDY', lastname: 'R.', initials: 'C.R.', boxid: '23', poolid: '1')
Box.create(firstname: 'MEGAN', lastname: 'V.', initials: 'M.V.', boxid: '24', poolid: '1')
Box.create(firstname: 'MIGUEL', lastname: ' ', initials: 'M.', boxid: '25', poolid: '1')
Box.create(firstname: 'THE RUPPLES', lastname: ' ', initials: 'T.R.', boxid: '26', poolid: '1')
Box.create(firstname: 'MIKE', lastname: 'T.', initials: 'M.T.', boxid: '27', poolid: '1')
Box.create(firstname: 'KATA', lastname: 'Z.', initials: 'K.Z.', boxid: '28', poolid: '1')
Box.create(firstname: 'ARIEL', lastname: 'D.', initials: 'A.D.', boxid: '29', poolid: '1')
Box.create(firstname: 'JUNIOR', lastname: 'G.', initials: 'J.G.', boxid: '30', poolid: '1')
Box.create(firstname: 'MAE', lastname: 'V.', initials: 'M.V.', boxid: '31', poolid: '1')
Box.create(firstname: 'GERRY', lastname: 'H.', initials: 'G.H.', boxid: '32', poolid: '1')
Box.create(firstname: 'GARY', lastname: 'E.', initials: 'G.E.', boxid: '33', poolid: '1')
Box.create(firstname: 'ERIC', lastname: 'Z.', initials: 'E.Z.', boxid: '34', poolid: '1')
Box.create(firstname: 'ARVIN', lastname: ' ', initials: 'AR', boxid: '35', poolid: '1')
Box.create(firstname: 'JOSIAH', lastname: ' ', initials: 'JO', boxid: '36', poolid: '1')
Box.create(firstname: 'O.J.', lastname: ' ', initials: 'O.J.', boxid: '37', poolid: '1')
Box.create(firstname: 'ROD', lastname: 'U.', initials: 'R.U.', boxid: '38', poolid: '1')
Box.create(firstname: 'DOY-DOY', lastname: ' ', initials: 'D.D.', boxid: '39', poolid: '1')
Box.create(firstname: 'MIKE', lastname: 'T.', initials: 'M.T.', boxid: '40', poolid: '1')
Box.create(firstname: 'RON', lastname: 'E.', initials: 'R.E.', boxid: '41', poolid: '1')
Box.create(firstname: 'JEFF', lastname: ' ', initials: 'JEFF', boxid: '42', poolid: '1')
Box.create(firstname: 'GREG', lastname: 'S.', initials: 'G.S.', boxid: '43', poolid: '1')
Box.create(firstname: 'JANICE', lastname: ' ', initials: 'JAN', boxid: '44', poolid: '1')
Box.create(firstname: 'KARL', lastname: ' ', initials: 'KAR', boxid: '45', poolid: '1')
Box.create(firstname: 'JOE', lastname: 'M.', initials: 'J.M.', boxid: '46', poolid: '1')
Box.create(firstname: 'FRANK', lastname: 'C.', initials: 'F.C.', boxid: '47', poolid: '1')
Box.create(firstname: 'ERIC', lastname: 'Z.', initials: 'E.Z.', boxid: '48', poolid: '1')
Box.create(firstname: 'JAY', lastname: ' ', initials: 'JAY', boxid: '49', poolid: '1')
Box.create(firstname: 'JAY', lastname: ' ', initials: 'JAY', boxid: '50', poolid: '1')
Box.create(firstname: 'DENNIS T.', lastname: ' ', initials: 'D.T.', boxid: '51', poolid: '1')
Box.create(firstname: 'ARVIN', lastname: ' ', initials: 'AR', boxid: '52', poolid: '1')
Box.create(firstname: 'LINDA', lastname: 'E.', initials: 'L.E.', boxid: '53', poolid: '1')
Box.create(firstname: 'ROD', lastname: 'U.', initials: 'R.U.', boxid: '54', poolid: '1')
Box.create(firstname: 'VICE', lastname: ' ', initials: 'V.', boxid: '55', poolid: '1')
Box.create(firstname: 'RAMIRO', lastname: ' ', initials: 'R.', boxid: '56', poolid: '1')
Box.create(firstname: 'MAE', lastname: 'V.', initials: 'M.V.', boxid: '57', poolid: '1')
Box.create(firstname: 'STEVE', lastname: 'R.', initials: 'S.R.', boxid: '58', poolid: '1')
Box.create(firstname: 'SANDI', lastname: 'E.', initials: 'S.E.', boxid: '59', poolid: '1')
Box.create(firstname: 'KATH', lastname: 'Z.', initials: 'K.Z.', boxid: '60', poolid: '1')
Box.create(firstname: 'DOY-DOY', lastname: ' ', initials: 'D.D.', boxid: '61', poolid: '1')
Box.create(firstname: 'CARTEL', lastname: ' ', initials: 'C.', boxid: '62', poolid: '1')
Box.create(firstname: 'O.J.', lastname: ' ', initials: 'O.J.', boxid: '63', poolid: '1')
Box.create(firstname: 'RON', lastname: 'E.', initials: 'R.E.', boxid: '64', poolid: '1')
Box.create(firstname: 'MANNY', lastname: 'U.', initials: 'M.U.', boxid: '65', poolid: '1')
Box.create(firstname: 'JUNIOR', lastname: 'G.', initials: 'J.G.', boxid: '66', poolid: '1')
Box.create(firstname: 'GARY', lastname: 'E.', initials: 'G.E.', boxid: '67', poolid: '1')
Box.create(firstname: 'JALI', lastname: ' ', initials: 'JAL', boxid: '68', poolid: '1')
Box.create(firstname: 'ARIEL', lastname: 'D.', initials: 'A.D.', boxid: '69', poolid: '1')
Box.create(firstname: 'DOY-DOY', lastname: ' ', initials: 'D.D.', boxid: '70', poolid: '1')
Box.create(firstname: 'SANDI', lastname: 'E.', initials: 'S.E.', boxid: '71', poolid: '1')
Box.create(firstname: 'KYLIE', lastname: ' ', initials: 'K.', boxid: '72', poolid: '1')
Box.create(firstname: 'JOE', lastname: 'M.', initials: 'J.M.', boxid: '73', poolid: '1')
Box.create(firstname: 'MIGUEL', lastname: ' ', initials: 'M.', boxid: '74', poolid: '1')
Box.create(firstname: 'FRANK', lastname: 'C.', initials: 'F.C.', boxid: '75', poolid: '1')
Box.create(firstname: 'MIKE', lastname: 'T.', initials: 'M.T.', boxid: '76', poolid: '1')
Box.create(firstname: 'GERRY', lastname: 'H.', initials: 'G.H.', boxid: '77', poolid: '1')
Box.create(firstname: 'JEFF', lastname: ' ', initials: 'JE', boxid: '78', poolid: '1')
Box.create(firstname: 'JOSE', lastname: 'B.', initials: 'J.B.', boxid: '79', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '80', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '81', poolid: '1')
Box.create(firstname: 'GTR', lastname: ' ', initials: 'GTR', boxid: '82', poolid: '1')
Box.create(firstname: 'FRANK', lastname: 'C.', initials: 'F.C.', boxid: '83', poolid: '1')
Box.create(firstname: 'WAYNE', lastname: ' ', initials: 'W.', boxid: '84', poolid: '1')
Box.create(firstname: 'ERNEST', lastname: 'B.', initials: 'E.B.', boxid: '85', poolid: '1')
Box.create(firstname: 'MEGAN', lastname: 'V.', initials: 'M.V.', boxid: '86', poolid: '1')
Box.create(firstname: 'CARTEL', lastname: ' ', initials: 'C.', boxid: '87', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '88', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '89', poolid: '1')
Box.create(firstname: 'RACE', lastname: ' ', initials: 'R', boxid: '90', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '91', poolid: '1')
Box.create(firstname: 'FRANK', lastname: 'C.', initials: 'F.C.', boxid: '92', poolid: '1')
Box.create(firstname: 'WAYNE', lastname: ' ', initials: 'W.', boxid: '93', poolid: '1')
Box.create(firstname: 'JAY', lastname: ' ', initials: 'JAY', boxid: '94', poolid: '1')
Box.create(firstname: 'JANICE', lastname: ' ', initials: 'JAN', boxid: '95', poolid: '1')
Box.create(firstname: 'DOY-DOY', lastname: ' ', initials: 'D.D.', boxid: '96', poolid: '1')
Box.create(firstname: 'RON', lastname: 'E.', initials: 'R.E.', boxid: '97', poolid: '1')
Box.create(firstname: 'EDLC', lastname: ' ', initials: 'E', boxid: '98', poolid: '1')
Box.create(firstname: 'RACE', lastname: ' ', initials: 'R', boxid: '99', poolid: '1')







